---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zachlava/public_html/
    - /bin/cp -R dist/my-site/* $DEPLOYPATH
    - /bin/cp -R package-lock.json $DEPLOYPATH
    - /bin/cp -R package.json $DEPLOYPATH
    - /bin/cp -R angular.json $DEPLOYPATH 